window:
  title: Alacritty

  class:
    instance: Alacritty
    general: Alacritty

  opacity: 0.80

  padding:
    x: 5
    y: 5

font:
  normal:
     family: FiraCode Nerd Font
     style: Regular

  bold:
      family: FiraCode Nerd Font
      style: Bold

  italic:
      family: FiraCode Nerd Font
      style: Italic

  bold_italic:
      family: FiraCode Nerd Font
      style: Bold Italic

  size: 10.0

colors:
   primary:
     background: '#0a0a0a'
     foreground: '#B8B9B4'

   normal:
     black: '#0A0A0A'
     red: '#939490'
     green: '#5E6E5C'
     yellow: '#B6B8B3'
     blue: '#727370'
     magenta: '#D1D1CB'
     cyan: '#636361'
     white: '#AAABA6'

   bright:
     black: '#2E2E2C'
     red: '#989995'
     green: '#636361'
     yellow: '#BBBDB8'
     blue: '#777875'
     magenta: '#D6D6D0'
     cyan: '#696966'
     white: '#AFB0AB'
